api:
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: "lucianovargas88@hotmail.com.br"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: "web"